### ISSUE TITLE
Particle structure creation problem for smaller mesh

### ISSUE THREAD

**Issue by kumargp** [SCOREC/particle_structures#13]
Crashes when creating 1 million particles in an element in smaller mesh, but succeeds in larger mesh. We don't know if this will be realistic need, though. Crashes for both when 10 M particles used, which may be expected given the memory.

extruded mesh with 16 planes
------------------------------------

Number of elements 401328
Initializing 1,000,000 impurity particles
terminate called after throwing an instance of 'std::runtime_error'
  what():  View bounds error of view elem_gids ( 401328 < 401328 )
Traceback functionality not available
Aborted (core dumped)

==========================================

extruded mesh with 64 planes
-----------------------------------
Number of elements 1605312
Initializing 1,000,000 impurity particles
 Ptcls in elId 183176
 ptcls/elem[183176] 1000000
Building SCS with C: 1 sigma: 2147483647 V: 1024
(suceeds ...)

**Comment by diamog** [comment]
I believe your problem is here: https://github.com/SCOREC/pumi-pic/blob/push/src/GitrmParticles.cpp#L55-L57. The elem_gids view is sized number of elements and the following parallel for is over numPtcls which is why it crashes for the smaller mesh.

As I've said before, the element gids passed into the SCS is the global identifier for each element. Since you are running a single process, you can just pass in an empty element_gids view (size 0) and it will run fine.
